config/routes.rb
Rails.application.routes.draw do


	mount Attachinary::Engine => "/attachinary"
	devise_for :users
	root to: 'pages#home'
  get '/dashboard', to: 'users#dashboard'
  get '/dashboard/edit', to: 'users#edit'
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post 'trees/update_trees', to: 'trees#update_trees', format: :js
  resources :trees do
    resources :bookings, only: [:new, :create, :show ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :tree
  validates :date_check_in, presence: true
  validates :date_check_out, presence: true
end

app/models/tree.rb
class Tree < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :users, through: :bookings
  validates :price_per_night, presence: true, numericality: true
  validates :capacity, presence: true, numericality: true
  # validates :location, presence: true
  validates :address, presence: true
  validates :title, presence: true



 # mount_uploader :photo, PhotoUploader
 has_attachments :photos, maximum: 3

 geocoded_by :address
 after_validation :geocode, if: :will_save_change_to_address?


  # search: min and max latidue & longitude
  scope :by_longitude, -> (min, max) { min && max ? where('longitude >= :min AND longitude <= :max', min: min, max: max) : all }
  scope :by_latitude, -> (min, max) { min && max ? where('latitude >= :min AND latitude <= :max', min: min, max: max) : all }

  API_RESULTS_LIMIT = 100

  def self.search(min_lat:, max_lat:, min_lng:, max_lng:)
    by_latitude(min_lat, max_lat).
    by_longitude(min_lng, max_lng).
    limit(API_RESULTS_LIMIT)
  end


end

app/models/user.rb
class User < ApplicationRecord
  has_many :trees
  has_many :bookings
  has_many :trees, through: :bookings
  validates :email, presence: true, uniqueness: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attachment  :avatar, accept: [:jpg, :png, :gif]
  # has_attachments :photos, maximum: 10
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, :except => [:home, :index, :show]
  include Pundit

   # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

    private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def show
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def new
    @booking = Booking.new
    @tree = Tree.find(params[:tree_id])
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @tree = Tree.find(params[:tree_id])
    @booking.tree = @tree
    @booking.total_price = (@booking.date_check_out - @booking.date_check_in).to_i * @tree.price_per_night
    @booking.user = current_user
    authorize @booking
    if @booking.save
      redirect_to tree_booking_path(@tree, @booking)
    else
      render :new
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:date_check_in, :date_check_out)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/trees_controller.rb
class TreesController < ApplicationController
  before_action :set_tree, only: [ :show, :update, :destroy ]
  skip_before_action :verify_authenticity_token, only: [:update_trees]

  def index
    if params[:search] == ""
      @trees = policy_scope(Tree)
    elsif params[:search] && !Tree.where(address: params[:search]).empty?
      @trees = policy_scope(Tree)
      tree = Tree.where(address: params[:search]).first
      min_lat = tree.latitude - 2
      max_lat = tree.latitude + 2
      max_lng = tree.longitude + 2
      min_lng = tree.longitude - 2
      @trees = Tree.search(min_lat: min_lat, max_lat: max_lat, min_lng: min_lng, max_lng: max_lng )
    else
      @trees = policy_scope(Tree)
    end

    # @map_trees = Tree.where.not(latitude: nil, longitude: nil)
    @markers = @trees.map do |tree|
      {
        lat: tree.latitude,
        lng: tree.longitude
        # infoWindow: { content: render_to_string(partial: "/flats/map_box", locals: { flat: flat }) }
      }
    end
    if params[:search]
      @trees_filter = params[:search]
    else
      @trees_filter = ""
    end
  end

  def update_trees
    skip_authorization
    # @trees = Tree.last(10)
    @trees = Tree.search(min_lat: params["minLat"].to_f - 2, max_lat: params["maxLat"].to_f + 2, min_lng: params["minLng"].to_f - 2, max_lng: params["maxLng"].to_f + 2)

    respond_to do |format|
      format.html { render 'trees/index' }
      format.js
    end


    end


    def show
      @tree = Tree.find(params[:id])
      authorize @tree
      if @tree.latitude && @tree.longitude
        @markers = [{
          lat: @tree.latitude,
          lng: @tree.longitude
          }]
        end

      end

      def new
        @tree = Tree.new
        authorize @tree
      end

      def create
        @tree = Tree.new(tree_params)
        @tree.user = current_user
        authorize @tree
        if @tree.save
          redirect_to tree_path(@tree)
        else
          render :new
        end
      end

      def edit
        set_tree
        authorize @tree
      end

      def update
        @tree.update(tree_params)
        authorize @tree
        redirect_to tree_path(@tree)
      end

      def destroy
        set_tree
        @tree.destroy
        authorize @tree
        redirect_to trees_path
      end

      private

      def set_tree
        @tree = Tree.find(params[:id])
      end

      def tree_params
        params.require(:tree).permit(:location, :price_per_night, :avalable, :capacity, :description, :title, :address, photos: [])
      end

    end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def dashboard
    @bookings = Booking.where(user_id: current_user.id).order(date_check_in: :asc)
    @trees = Tree.where(user_id: current_user.id)
    authorize current_user
  end

  def edit
    @user = current_user
    authorize @user
  end

  def update
    @user = current_user
    @user.update(user_params)
    authorize @user
    redirect_to dashboard_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :phone_number, photo: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="text-center" style="min-height: 70vh">
  <h2>Book your Tree</h2>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-sm-offset-3">
        <%= simple_form_for [@tree, @booking] do |f|%>
        <%= f.input :date_check_in, as: :date, label: "Check In Date", placeholder: "Check In Date" %>
        <%= f.input :date_check_out, as: :date, label: "Check Out Date", placeholder: "Check Out Date" %>
        <%= f.button :submit, "Book", class: "btn-success" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="text-center confirmation-view">
  <h2>Your Reservation has been confirmed </h2>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-sm-offset-3">
        <p>You will stay in <%= @booking.tree.title %> for <strong><%= (@booking.date_check_out-@booking.date_check_in).to_i %></strong> days</p>
        <p>The price per night in our tree is <strong> <%= @booking.tree.price_per_night %></strong> <%= image_tag("acorn.svg", height: 20) %> </p>
        <p>Total price is <strong><%= (@booking.date_check_out-@booking.date_check_in).to_i * @booking.tree.price_per_night %>  <%= image_tag("acorn.svg", height: 20) %> </strong> </p>
        <p>An email with the details of your reservation has ben sent to <%= current_user.email %></p>
      </div>
    </div>
  </div>
  <%= link_to "Back to search", root_path, class: "btn-medium" %>
  <%= link_to "My Dashboard", dashboard_path, class: "btn-medium" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>treeBnB</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <%= favicon_link_tag 'favicon.ico' %>

  </head>
  <body>
    <%= render 'shared/navbar' %>
   <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>



    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= cloudinary_js_config %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_pack_tag "map" %>
  </body>
</html>

app/views/pages/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(135deg, rgba(154, 122, 32, 0.7) 0%, rgba(47, 85, 33, 0.8) 50%), url(https://images.pexels.com/photos/531323/pexels-photo-531323.jpeg?w=1260&h=750&auto=compress&cs=tinysrgb);">
  <div class="banner-content">
    <h1>Rent awesome trees around the world</h1>
    <%= render 'homepage_form' %>

  </div>
</div>

app/views/pages/_homepage_form.html.erb
<div class="homepage-form">
	<form action="/trees">
		<div class="search-box">
			<label for="search"></label>
			<input type="text" id="search" placeholder="Enter your dream city" name="search">
		</div>
		<div class="search-button">
			<input type="submit" value="Search">
		</div>
	</form>
</div>

app/views/pages/home.html.erb
<%= render 'banner' %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
	<div class="footer-icons">
		<a href="#"><i class="fab fa-github"></i></a>
		<a href="#"><i class="fab fa-instagram"></i></a>
		<a href="#"><i class="fab fa-facebook"></i></a>
		<a href="#"><i class="fab fa-twitter"></i></a>
		<a href="#"><i class="fab fa-linkedin"></i></a>
	</div>
	<div class="footer-links">
		<ul>
			<li>Discover</li>
			<li><a href="#">Gift Cards</a></li>
			<li><a href="#">TreeBnB Squirrels</a></li>
		</ul>
		<ul>
			<li>TreeBnB</li>
			<li><a href="#">Jobs</a></li>
			<li><a href="#">Investor Relations</a></li>
		</ul>
		<ul>
			<li>Hosting</li>
			<li><a href="#">Why Host</a></li>
			<li><%= link_to 'Become a host', new_tree_path %></li>
			<li><a href="#">Hospitality</a></li>
			<li><a href="#">Community Center</a></li>
		</ul>
	</div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

    <!-- Avatar with dropdown menu -->

    <%= link_to 'Become a host', new_tree_path, class: "navbar-wagon-item green" %>

    <div class="navbar-wagon-item">

      <div class="dropdown">
        <%= image_tag "https://assets.atlasobscura.com/article_images/800x/17628/image.jpg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to dashboard_path do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
    <% else %>
    <!-- Login link (when logged out) -->
    <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/trees/_trees_list.html.erb
<% trees.each do |tree| %>
<div class="index-search-result">
  <% if tree.photos.first %>
  <div class="result-image" style="background-image: linear-gradient(135deg, rgba(0,0,0,0.6) 0%, rgba(0,0,0,0.3) 50%), url('<%= cl_image_path tree.photos.first.path, width: 200, height: 150, crop: :fit %>');">
  </div>
  <% end %>
  <div class="result-title">
    <p><%= link_to "#{tree.title}", tree_path(tree) %></p>
  </div>
  <div class="result-location">
    <p><%= tree.location.truncate(25) %></p>
  </div>
  <div class="result-description">
    <p><%= tree.description.truncate(140) %></p>
  </div>


  <%# pictures = [image_tag "1.jpg", image_tag "2.jpg", image_tag "3.jpg", image_tag "4.jpg", image_tag "5.jpg"] %>
<% pictures = ["1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg"] %>

  <div class="result-avatar">
   <%#= pictures.sample %>
   <%= image_tag(pictures.sample, height: 100, width: 100) %>
    <!-- <img src="http://i.pravatar.cc/75?u=<%= rand(20..500) %>" alt=""> -->
    <%#= cl_image_tag current_user.avatar, width: 100, height: 100, radius: :max %>
  </div>
  <div class="result-price">
    <p>Price/night <%= tree.price_per_night %> <%= image_tag("acorn.svg", height: 15) %></p>
  </div>
  <div class="result-review">
    <p> <% a=rand()+(6..9).to_a.sample %>
      <%= a.round(1) %> *
    </p>
  </div>
</div>
<% end %>

app/views/trees/edit.html.erb
<div class="text-center">
  <h2>Change your tree</h2>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-sm-offset-3">
        <%=  simple_form_for @tree do |f|%>
        <%= f.input :location, label: false, placeholder: "Enter name of the city" %>
        <%= f.input :title, label: false, placeholder: "Enter the title of your tree" %>
        <%= f.input :address, label: false, placeholder: "Enter full address of your tree" %>
        <%= f.input :description, label: false, placeholder: "Enter description" %>
        <%= f.input :capacity, label: false, placeholder: "How many squirrels can stay here?" %>
        <%= f.input :price_per_night, label: false, placeholder: "Price per night" %>
        <%= f.button :submit, "Update your tree", class: "btn-success" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/trees/index.html.erb
<% unless @trees.empty? %>
<% content = open("https://api.darksky.net/forecast/fa5d94b5a83673b3ee1d802e80dfc7ee/#{@trees.last.latitude},#{@trees.last.longitude}?exclude=[currently,minutely,hourly,alerts,flags]&units=si").read %>
<% results = JSON.parse(content) %>
<h5>The weather in <%= params[:search] %></h5>
<div class="wrapper-weather">
  <!-- comment la -->
  <ul style='list-unstyled'>
    <% results["daily"]["data"][0..3].each do |item| %>
    <li class="weather-box">
      <p>
        <%= Time.at(item["time"]).day %>.<%= Time.at(item["time"]).month %>.<%= Time.at(item["time"]).year %>
      </p>
      <% if item["icon"] == "partly-cloudy-day" %>
      <%= image_tag "partly_cloudy.png", height: 35  %>
      <% elsif item["icon"] == "partly-cloudy-night" %>
      <%= image_tag "partly_cloudy.png", height: 35  %>
      <% elsif item["icon"] == "clear-day" %>
      <%= image_tag "clear.png", height: 35  %>
      <% else %>
      <%= image_tag "snow.png", height: 35  %>
      <% end %>
      <p><%= item["temperatureHigh"].round(1) %>°C / <%= item["temperatureLow"].round(1) %>°C</p>
      <p><%= item["summary"] %></p>
    </li>
    <% end %>
  </ul>
</div>

<% end %>

<div class="homepage-form">
  <form action="/trees">
    <i class="fa fa-search"></i>
    <div class="search-box">
      <label for="search"></label>
      <input type="text" id="search" placeholder="Change your destination" name="search">
    </div>
    <div class="search-button">
      <input type="submit" value="Search">
    </div>
  </form>
</div>
<div class="main-container">
  <div class="wrapper-index">

    <div id="trees-list" class="index-search">
      <%= render "trees_list", trees: @trees %>
    </div>

    <div
    id="map"
    style="width: 100%;
    height: 50%;"
    data-markers="<%= @markers.to_json %>"
    data-trees-path="<%= trees_update_trees_path %>"
    data-trees-filter="<%= @trees_filter %>"
    ></div>

  </div>
</div>

app/views/trees/new.html.erb
<div class="text-center wrapper-new">
  <h2>Add your lovely tree</h2>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-sm-offset-3">
        <%=  simple_form_for @tree do |f|%>

      <!--   <%#= f.input :photo_cache, as: :hidden %> -->
        <%= f.input :location, label: false, placeholder: "Enter name of the city" %>
        <%= f.input :address, label: false, placeholder: "Enter full address of your tree" %>
        <%= f.input :title, label: false, placeholder: "Give a title to your tree" %>
        <%= f.input :description, label: false, placeholder: "Enter description" %>
      <%= f.input :capacity, label: false, placeholder: "How many squirrels can stay here?" %>
      <%= f.input :price_per_night, label: false, placeholder: "Price per night" %>
      <%= f.input :photos, as: :attachinary %>

      <%= f.button :submit, "Add your tree", class: "btn-success" %>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/trees/show.html.erb
 <div class="container text-center">
 	<div class="grid">
 		<div class="card-grid map-section">
 			<div
 			id="map"
 			style="width: 100%; height: 600px;"
 			data-markers="<%= @markers.to_json %>"
 			></div>
 		</div>

 		<% @tree.photos.each do |photo| %>
 		<div class="card-grid image-section">
 			<%= cl_image_tag photo.path, class: "grid-image" %>
 		</div>
 		<% end %>


 		<div class="card-grid descr-section">
 			<div class="card-content text-left">
 				<h3><%= @tree.title %> </h3>
 				<p> Location: <%= @tree.location %></p>
        <p> Address: <%= @tree.address %></p>
        <p><%= @tree.description %></p>
 				<p> Capacity: <%= @tree.capacity %> <i> <small> squirrels </small> </i></p>
 				<p> Price / night: <%= @tree.price_per_night %><i> <small> <%= image_tag("acorn.svg", height: 20) %></small>  </i></p>
 				<%= link_to "book", new_tree_booking_path(@tree), class: "btn btn-success" %>

 			</div>
 		</div>

 		<div class="container-flex tools-section card-grid">
 			<%= link_to tree_path(@tree), method: :delete do %>
 			<%= icon('fas', 'trash') %> <span class="text-small">Delete</span>
 			<% end %>
 			<%= link_to edit_tree_path(@tree) do %>
 			<%= icon('fas', 'edit') %> <span class="text-small">Edit</span>
 			<% end %>
 			<%= link_to "/trees?search=#{@tree.location}" do %>
 			<%= icon('fas', 'arrow-left') %> <span class="text-small">Go back</span>
 			<% end %>

 		</div>

 	</div>
 </div>

app/views/trees/update_trees.js.erb
var treesList = document.getElementById('trees-list');
treesList.innerHTML = "<%= j render 'trees_list', trees: @trees %>"

app/views/users/dashboard.html.erb
<div class="wrapper-dashboard">
  <div class="dashboard-info">
   <h1>Name: <%= current_user.name %> </h1>
   <h3>Phone nnumber:<%= current_user.phone_number %> </h3>
   <h4>email: <%= current_user.email %> </h4>
 </div>
 <div class="dashboard-bookings">
  <div class="bookings-header">
    <h1>My Bookings</h1>
  </div>
  <% @bookings.each do |booking| %>
  <div class="panel panel-default">
    <div class="panel-heading style="height: 46px;"><%= link_to booking.tree.title, tree_booking_path(booking.tree.id, booking.id) %></div>
    <div class="panel-body" style="height: 55px;">
      <p>Check in: <%= booking.date_check_in %> , Check out: <%= booking.date_check_out %>. Total price: <%= booking.total_price %> <%= image_tag("acorn.svg", height: 20) %></p>  </div>
    </div>
    <% end %>
  </div>
  <div class="dashboard-trees">
    <div class="trees-header">
      <h1>My Trees</h1>
    </div>
    <% @trees.each do |tree| %>
    <div class="panel panel-default">
      <div class="panel-heading" style="height: 46px;"><%= link_to tree.description, tree_path(tree) %></div>
      <div class="panel-body" style="height: 55px;">
        Panel content
      </div>
    </div>
    <% end %>
  </div>
  <div class="dashboard-buttons" style="text-align:center;">

    <%= link_to "Edit Profile", dashboard_edit_path, class: "btn-medium" %>
    <%= link_to "Search", root_path, class: "btn-medium"  %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="text-center">
  <h2>Edit your Profile</h2>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-sm-offset-3">
        <%=  simple_form_for @user do |f|%>
        <%= f.input :name, label: false, placeholder: "Name" %>
        <%= f.input :phone_number, label: false, placeholder: "Phone Number" %>
        <%= f.button :submit, "Submit", class: "btn-success" %>
        <% end %>
      </div>
    </div>
  </div>
</div>